[package]
name = "bounty-cli"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
clap = { version = "4.4", features = ["derive", "env"] }
clap_complete = "4.4"
color-eyre = { version = "0.6.3", features = ["capture-spantrace"] }
eyre = "0.6.12"
git2 = { version = "0.20.0" }
octocrab = { version = "0.42.1" }
tokio = { version = "1.36", features = ["full"] }
tracing = "0.1"
tracing-error = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints.clippy]
complexity = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "z"
strip = true
panic = "abort"
