name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    
    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Log in to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: nix build .#docker

    - name: Push Docker image
      if: github.event_name != 'pull_request'
      run: |
        # Push with commit SHA tag
        skopeo copy docker-archive:$(readlink -f result) docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        
        # Push as latest for main branch
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          skopeo copy docker-archive:$(readlink -f result) docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        fi
        
        # Push with version tag if this is a tag
        if [[ ${{ github.ref_type }} == 'tag' ]]; then
          skopeo copy docker-archive:$(readlink -f result) docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
        fi 