name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    
    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Log in to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push AMD64 image
      run: |
        # Build AMD64 image
        nix build .#docker-amd64
        
        # Push with architecture-specific tags
        skopeo copy docker-archive:$(readlink -f ./result) \
          docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-amd64
        
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          skopeo copy docker-archive:$(readlink -f ./result) \
            docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-amd64
        fi
        
        if [[ ${{ github.ref_type }} == 'tag' ]]; then
          skopeo copy docker-archive:$(readlink -f ./result) \
            docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-amd64
        fi

  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    
    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Log in to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push ARM64 image
      run: |
        # Build ARM64 image
        nix build .#docker-arm64
        
        # Push with architecture-specific tags
        skopeo copy docker-archive:$(readlink -f ./result) \
          docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-arm64
        
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          skopeo copy docker-archive:$(readlink -f ./result) \
            docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-arm64
        fi
        
        if [[ ${{ github.ref_type }} == 'tag' ]]; then
          skopeo copy docker-archive:$(readlink -f ./result) \
            docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-arm64
        fi

  create-manifest:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create and push manifest lists
        run: |
          # Create manifest for SHA
          docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --amend ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-amd64 \
            --amend ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-arm64
          docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-amd64 --os linux --arch amd64
          docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-arm64 --os linux --arch arm64 --variant v8
          docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            # Create manifest for latest
            docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
              --amend ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-amd64 \
              --amend ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-arm64
            docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-amd64 --os linux --arch amd64
            docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-arm64 --os linux --arch arm64 --variant v8
            docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          fi
          
          if [[ ${{ github.ref_type }} == 'tag' ]]; then
            # Create manifest for version tag
            docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
              --amend ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-amd64 \
              --amend ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-arm64
            docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-amd64 --os linux --arch amd64
            docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-arm64 --os linux --arch arm64 --variant v8
            docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          fi 