name: Nix Build and Cache

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-native:
    strategy:
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            platform: x86_64-linux
          # macOS builds (both Intel and Apple Silicon)
          - os: macos-latest
            platform: x86_64-darwin
          - os: macos-14 # macOS 14 runner has Apple Silicon
            platform: aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Build native package
        run: nix build .#default

      - name: Upload to Cachix
        uses: cachix/cachix-action@v14
        with:
          name: ghbountybot
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pushFilter: ".*"
